// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void* __swift_bridge__$renderer_new(void* layer_ptr, uint32_t width_px, uint32_t height_px, float pixels_per_point);
void __swift_bridge__$renderer_free(void* ptr);
void __swift_bridge__$renderer_resize(void* ptr, uint32_t width_px, uint32_t height_px);
void __swift_bridge__$renderer_set_pixels_per_point(void* ptr, float pixels_per_point);
void __swift_bridge__$renderer_render(void* ptr, double time_seconds);
void __swift_bridge__$renderer_touch_began(void* ptr, float x_pt, float y_pt);
void __swift_bridge__$renderer_touch_moved(void* ptr, float x_pt, float y_pt);
void __swift_bridge__$renderer_touch_ended(void* ptr, float x_pt, float y_pt);
bool __swift_bridge__$renderer_has_pending_notification(void* ptr);
void* __swift_bridge__$renderer_notification_title(void* ptr);
void* __swift_bridge__$renderer_consume_notification_body(void* ptr);
bool __swift_bridge__$renderer_wants_keyboard(void* ptr);
void __swift_bridge__$renderer_insert_text(void* ptr, void* text);
void __swift_bridge__$renderer_delete_backward(void* ptr);
void __swift_bridge__$renderer_key_event(void* ptr, int32_t key_code, int32_t modifier_flags, bool pressed);
void __swift_bridge__$renderer_scroll(void* ptr, float dx, float dy);
void __swift_bridge__$renderer_pointer_moved(void* ptr, float x_pt, float y_pt);
void __swift_bridge__$renderer_set_save_directory(void* ptr, void* path);
bool __swift_bridge__$renderer_has_pending_share(void* ptr);
void* __swift_bridge__$renderer_consume_pending_share_path(void* ptr);


